# Generated by Django 4.0.5 on 2022-06-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='회사_id')),
                ('company_name', models.CharField(max_length=50, verbose_name='회사명')),
                ('country', models.CharField(max_length=50, verbose_name='국가')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='사용자_id')),
                ('user_name', models.CharField(max_length=20, verbose_name='사용자명')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='채용공고_id')),
                ('position', models.CharField(max_length=100, verbose_name='채용포지션')),
                ('prize', models.IntegerField(verbose_name='채용보상금')),
                ('content', models.TextField(verbose_name='채용내용')),
                ('skill', models.CharField(max_length=100, verbose_name='사용기술')),
                ('company_id', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='post.company')),
            ],
        ),
    ]
